### PR TITLE
Make some parameters optional

### PR DESCRIPTION
**Pull request by alexalikiotis**
Making some parameters optional instead of having `string | null | undefined` as the type.

@helio-frota don't delete this branch, I've got more PRs coming...

### CODE REVIEW

**Review by helio-frota — APPROVED** [review]

**Comment by helio-frota** [comment]
@alexalikiotis LGTM.

Also what do you think we keep some pattern in filenames like

license [cli] -> licenseCmd.ts -> license.ts

check [cli] -> checkCmd.ts -> checker.ts

instead of

check [cli] -> checkCmd.ts -> package.ts

?

**Comment by alexalikiotis** [comment]
@helio-frota While I was thinking the same I had a problem with the words used. For example, `license` is a noun, and `check` is a verb (in the commands section). There is a word type difference there that does not look good to my eyes. 

Also, the check word is a little vague on the meaning for example check what ?? license ?? package ?? (to an outsider that would be confusing)

I don't have a solution to propose yet but do you think we should rethink our naming strategy ??

**Comment by helio-frota** [comment]
We can change that to `PackageChecker` and `LicenseFinder`
and for the command line options we can abbreviate 

So we can have something like

`oratrix licenses` -->  `LicenseFinderCmd` --> `LicenseFinder`
`oratrix check` -->  `PackageCheckerCmd` --> `PackageChecker`

makes sense ?

**Comment by helio-frota** [comment]
So let's imagine we have some "validate" command in future

`oratrix validate --> ValidatorCmd --> Validator`

**Comment by helio-frota** [comment]
We can also change to `oratrix find-licenses` to make that look like an action, that will call a "LicenseFinderCmd" thing

**Comment by alexalikiotis** [comment]
I would suggest something like: `verb -> verb + Cmd -> module-name` if this sounds possible

**Comment by alexalikiotis** [comment]
@helio-frota I will open another issue for the naming discussion since it's not something blocking for now and also other people can share their opinion

**Pull request merged**
