### PR TITLE
src: adding a Report class do deal with cli-table3

### PR DESCRIPTION
**Pull request by helio-frota**
Refactor to introduce a Report class to deal with cli-table3 tables.
That is also enable us to easily write test to cover the reports and
core/business layer that don't need to deal with reporting data.

### CODE REVIEW

**Comment by helio-frota** [comment]
relates to #42

**Comment by alexalikiotis** [comment]
@helio-frota Instead of returning a `string[]` as a result from the validator you can return an object of type Report.
```ts
interface Report {
  required: Record<string, unknown>;
  missing: string[];
}
```

so then you can also have the required fields object to pass as param to the createValidatorReport method (this is the easiest solution because otherwise we'll have to pull the fieldloader to the validatorCmd and that will require a bigger refactoring).

**Comment by helio-frota** [comment]
@alexalikiotis that is because I don't know yet if `runOrganizationCheck` is supposed to return the same type as `runLocalCheck`.
also I think the `run` function returns a concise result which is the difference found between the required fields and the current fields. Which also makes the validator tests clear when having a concise result:

```
  it('Should return the validation data', async () => {
    const result = await validator.run();
    assert.ok(result.length > 0);
  });

  it('Should contain missing description field', async () => {
    const result = await validator.run();
    assert.strictEqual(result[0], 'description');
  });
```

makes sense ?

**Comment by alexalikiotis** [comment]
@helio-frota yeah you're right. Let's leave it as is for now and when I finish the implementation of the `runOrganizationCheck ` method we can see our options then.

**Review by alexalikiotis — APPROVED** [review]

**Pull request merged**
